### ISSUE TITLE
Not too fast.

### ISSUE THREAD

**Issue by XmartySS** [Sfupu/Solana-Pump-Fun-Sniper-Bot#3]
Please implement gRPC and NEXTBLOCK. It will improve the buying speed because it always buys on the fourth or fifth candle. It should at least buy on the first or second candle.

**Comment by Sfupu** [comment]
use a good / premium rpc and your snipes would be in the first candle

**Comment by XmartySS** [comment]
I am using Helius developer RPC. Do I need something better than this?

**Comment by XmartySS** [comment]
> use a good / premium rpc and your snipes would be in the first candle

I am using Helius developer RPC. Do I need something better than this?
